# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "public_network"
  config.vm.provision "shell", path:"script.sh"
  config.vm.define "sdk5" do |sdk5|
   sdk5.vm.box = "centos/7"
   sdk5.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  
   end
  end
end
